microsoft/azure-devops-mcp

package.json
Configure access as public. Required pre-step to publish the package into npmjs.
=> chore: publishConfig access to "public"

README.md
This pull request adds a helpful resource to the `README.md` file to assist users in quickly setting up GitHub Copilot Agent Mode.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R156-R157): Included a link to a quick start video to help users get up and running with GitHub Copilot Agent Mode in under two minutes.
None
None
Manual testing
=> [docs]: Add quick start video link to README for easier onboarding

src/tools.ts
Register work tools in tools.ts. That toolset was missing.
No real risk
Fixed code and re-ran to ensure toolsets were registered. Ran tests.
=> fix: Ensure work tools are configured in the tool setup

.github/workflows/build.yml, .github/workflows/codeql.yml, .github/workflows/dependency-review.yml, .github/workflows/version-update.yml
To mitigate security concerns, we have made changes to the workflows to use specific action versions and added harden-runner steps to improve security.
- Pinning GitHub Actions to full commit shas
Following best practices outlined in the official GitHub documentation on [Security Hardening for GitHub Actions](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions) all GitHub Action steps have been updated to use full-length commit SHAs instead of mutable tags using [Harden-Runner](https://github.com/step-security/harden-runner).
(for example; `- uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2` instead of `- uses: actions/checkout@v4`)
This ensures that the exact, immutable …
=> update workflows to use specific action versions and adding harden-runner steps to improve security

src/tools/builds.ts
Add the option to specify build parameters to the build_run_build tool. Original API that was used did not expose this option, so I had to go in a roundabout way (using the Pipelines API) to be able to pass build parameters.
Fixes #72 .
/
Manually tested by calling build_run_build for a pipeline with 0, 1, and 2 parameters.
=> Option to specify build parameters in build_run_build tool (Issue #72)

src/tools/core.ts, src/tools/repos.ts
Adding the option to filter projects and repos by parts of their names.
Part of #113 .
/
Tested manually.
=> Option to filter repos and projects by parts of their names (Issue #113)

.github/workflows/version-update.yml
Potential fix for [https://github.com/microsoft/azure-devops-mcp/security/code-scanning/4](https://github.com/microsoft/azure-devops-mcp/security/code-scanning/4)
To fix the issue, we need to add a `permissions` block to the workflow. This block should specify the least privileges required for the workflow to function correctly. Based on the operations performed in the workflow, the following permissions are necessary:
- `contents: read` for reading repository contents.
- `pull-requests: write` for interacting with pull requests.
- `packages: write` for updating the package version and pushing tags.
The `permissions` block can be added at the root level of the workflow to apply to all jobs, or within the specific job (`update-version`) to limit its scope. In this case, adding it at the …
=> Potential fix for code scanning alert no. 4: Workflow does not contain permissions

src/tools/repos.ts
Limiting the number of results for repo tools in order to not overload the LLM.
Fixes #169 .
/
Tested manually a few of the tools.
=> Limit number of results for repo tools (Issue #169)

CONTRIBUTING.md
This simply adds open in Codespaces button so that contributors can easily make changes to this repository without having to clone it or set it up in local.
=> Add open in codespaces button to contribution guide

test/src/tools/wiki.test.ts
Improve Wikis code coverage from;
```sh
wikis.ts  |     100 |    70.58 |     100 |     100 | 39,69-89,110,145
```
to
```sh
File            | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s …
```
=> add wikis tests to improve code coverage

test/src/tools/workitems.test.ts
Improve WorkItems code coverage from;
```sh
workitems.ts  |   66.66 |    26.47 |   56.66 |   68.45 | 34-54,301,421,428-430,499-537,565-609,625-668
```
to
```sh
File            | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line …
```
=> add workitems tests to improve code coverage

src/useragent.ts
Adding missing header to the useragent.ts file to fix linter warnings
None
None
Open the useragent.ts file and see the linter warnings gone
=> chore: add missing copyright and license comments to useragent.ts

test/src/tools/builds.test.ts
Improve Build code coverage from;
```sh
builds.ts     |   40.29 |    28.57 |      20 |   39.39 | 66-88,102-106,161-187,201-205,222-226,243-247,263-286,300-304
```
to
```sh
File            | % Stmts | % Branch | % Funcs | % Lines | …
```
=> add build tests to improve code coverage

docs/HOWTO.md, src/tools/workitems.ts, test/src/tools/workitems.test.ts
Updated `create_work_item` to accept a `format` param so that you can set large text fields to use markdown. By default it is HTML. Also note, there is not good way on create to know if the field is a large text field or not. So it is going to assume the LLM knows what you ared doing based on your prompt. As a secondary check, we are looking at the value and if it is greater than 50 characters, it is safer to assume it is a large text field. Worse case, the opp will fail if you try and set a field to markdown that is not large text.
Updated `update_work_items_batch` as well to take format
Should be fine, no risks
updated tests and ran thru manual tests
=> updated create_work_item to support markdown format in large text fields

src/tools/workitems.ts, test/src/tools/workitems.test.ts
Changed param from project to projectid. Looks like only projectid is accepted when adding link to PR.
None
Updated automated tests and tested manually
=> fix: to link work items to pr

src/tools/workitems.ts, src/utils.ts, test/src/tools/workitems.test.ts
Added support of markdown for work item comments.
[Add work item comments API reference](https://learn.microsoft.com/en-us/rest/api/azure/devops/wit/comments/add-work-item-comment?view=azure-devops-rest-7.2&tabs=HTTP)
#66
None
Tested with `Claude Sonnet 4`.
Tried adding comments containing markdown or HTML content or just a plain text. It successfully uses the format parameter in most of the cases.
=> Added support of markdown for work item comments 

src/tools/workitems.ts, test/src/tools/workitems.test.ts
Adding link types for affects and affected by
None
Updated tests and manual check
=> Support for affects and affected by for adding work item links

src/tools/repos.ts
Added the `includeWorkItemRefs` param to include work items references linked to the PR.
how it looks in output json:
```json
"workItemRefs": [
{
"id": "1",
"url": "https://dev.azure.com/localconst-org/_apis/wit/workItems/1"
},
{
"id": "2",
"url": "https://dev.azure.com/localconst-org/_apis/wit/workItems/2"
}
],
```
#274 
Not actually a risk, but a note that to get full info about WIs agent will need to use another tools.
Tested on: GH Copilot in VSCode with gpt-4.1
1. Built server with changes
2. Configured it for VSCode
3. Created several test work items
4. Created test PR
5. Linked WIs to PR
6. Made call:  "get all PR's attached work items: <PR url>"
7. Observed tool call. Verified params included new `includeWorkItemRefs`
8. Observed tool call result. Verified work items are included …
=> Added `includeWorkItemRefs` param to the `repo_get_pull_request_by_id` tool

src/tools/workitems.ts, test/src/tools/workitems.test.ts
Added stack rank to list of returned fields so that it can be used to re-order a backlog easier
None
Manual validation and re-ran tests
=> Add stackrank to fields list for batch fetch by id

src/tools/repos.ts
This pull request enhances the `create_pull_request` tool in `src/tools/repos.ts` to support creating pull requests from forked repositories. The changes include adding a new parameter for specifying the fork repository ID and updating the logic to handle this parameter when creating pull requests.
Fixes #254 
none
Tested manually - managed to create a PR from a forked repo into the original one.
=> feat: add support for fork source repository in pull request creation (Issue 254)

src/tools/workitems.ts, test/src/tools/workitems.test.ts
Added a transformation on get work items in batch to only show the AssignedTo value and not a complex object
N/A
Manual tests. Updated automated tests
=> AssignedTo transformation for get work items in batch

README.md, docs/EXAMPLES.md, src/tools/workitems.ts, test/src/tools/workitems.test.ts
Added tool and tests to remove a link from a work item in batch. Meaning you can remove several links at once.
N/A
Added all new automated tests and tested manually. Will post video and prompts in follow-up commits or PR
=> Adding work_item_unlink to remove links from a work item

README.md, src/tools/repos.ts, test/src/tools/repos.test.ts
- Add repo_update_pull_request tool for updating PR title, description, draft status, and target branch
- Update documentation to reflect new tool capabilities
- Add validation to ensure at least one field is provided for update
- Support partial updates with optional parameters
[322](https://github.com/microsoft/azure-devops-mcp/issues/322)
- May cause confusion with similar `update_pull_request_status` and `update_pull_request_reviewers`, neither of those operations can be accomplished with the underlying API
- Been using it for a little over a week for personal uses. 
- src/tools/repos.test.ts (some very loose unit tests I let copilot author)
=> Add pull request update tool

src/tools/workitems.ts, test/src/tools/workitems.test.ts
Added new optional `fields` param when getting work items by id in batch
N/A
Updated manual tests. manual and copilot testing
=> Added optional fields param to get work items in batch

.github/workflows/build.yml
Build pipeline fails when the version information in the `version.ts` mismatches with the version information in the `package.json`
_Example error can be seen here; https://github.com/microsoft/azure-devops-mcp/actions/runs/16681842913/job/47222110601?pr=387#step:9:21_
Error message reads `Version mismatch detected. Please run 'npm run build' to update version.ts and add changes to the commit.`
But, there is no `npm run build` command in the `static-code-analysis` job, and also, `npm run build` would not fix this issue.
Error message fails to inform user to update version information in the `version.ts` file.
This PR fixes it.
N/A
None
Ran the commands on local computer
=> Fix error message in the build pipeline

docs/EXAMPLES.md
adding example on how to add artifact links to a work item
N/A
None
Manual review
=> docs: enhance examples for adding artifact links to work items

src/tools/workitems.ts, test/src/tools/workitems.test.ts
The function `get_work_items_batch_by_ids` transforms the field `System.AssignedTo` to contain a simple `name <email>`. With pull request #385 , users can choose returned fields. It would be great to transform all possible identity fields:
- System.AssignedTo
- System.CreatedBy
- System.ChangedBy
- System.AuthorizedAs
- Microsoft.VSTS.Common.ActivatedBy
- Microsoft.VSTS.Common.ResolvedBy
- Microsoft.VSTS.Common.ClosedBy
The proposed implementation leverages a list of known identity fields. An alternative would be to detect if the field looks like an identity. The risk is that it might find false positives.
#409 
_Replace_ by possible risks this pull request can bring you might have thought of
- Added new unit test
=> Transform all possible identity fields to formatted strings in wit_get_work_items_batch_by_ids

src/tools/testplans.ts, test/src/tools/testplan.test.ts
=> Explicit instructions for expected result format

src/tools/repos.ts, test/src/tools/repos.test.ts
Adding option to filter branches by name when listing branches.
When getting branches, not all branches will be fetched and then filtered on the client side, but we'll only fetch the relevant branch.
/
Manually tested, and updated tests.
=> Better filtering in branch tools

src/tools/repositories.ts, test/src/tools/repositories.test.ts
Adding `/` by default to filepaths when creating threads.
Fixes #494 
/
Fixes and added tests, manually tested.
=> Adding `/` by default to filepaths when creating threads (Issue 494)

src/tools/wiki.ts, test/src/tools/wiki.test.ts
According to the official documentation (https://learn.microsoft.com/en-us/rest/api/azure/devops/wiki/pages/create-or-update?view=azure-devops-rest-7.1&tabs=HTTP) following fields are required;
- versionDescriptor.versionType
- versionDescriptor.version
`versionType` field could be `branch` and `version` field could be the name of the `branch` that wiki is published to.
Default branch name for wikis is; `wikiMaster`
Fixes #490 
None
Run `npm test`
=> add branch parameter to configureWikiTools for wiki page operations

README.md, src/tools/test-plans.ts, test/src/tools/test-plan.test.ts
Adding testplan tool for creating test suite
498, https://github.com/microsoft/azure-devops-mcp/issues/498
Adding new test plan tool, no framework level risk
In VsCode,
=> Add test plans tool for create test suite

docs/GETTINGSTARTED.md
This pull request makes a minor update to the table of contents in the `docs/GETTINGSTARTED.md` file to fix the anchor link for the Visual Studio 2022 & GitHub Copilot section. The change ensures the link matches the correct section heading.
n/a
N/a
Manual testing
=> fix: correct link in Getting Started guide for Visual Studio 2022
