microsoft/azure-devops-mcp

src/index.ts
This PR addresses the following 2 issues
https://github.com/microsoft/azure-devops-mcp/issues/48
https://github.com/microsoft/azure-devops-mcp/issues/47
_Replace_ by possible risks this pull request can bring you might have thought of
_Replace_ with use cases tested and models used
=> Removing console logs and correcting the version number in index.ts

docs/HOWTO.md
Update video links for Azure DevOps MPC Server instructions
N/A
N/A
=> [docs]: Update video links for Azure DevOps MPC Server instructions

.devcontainer/devcontainer.json
Fixing `openFiles` customization setting in `devcontainer` config, and, fixing formatting, indentation.
Fixes #40 
N/A
Open the repo in a DevContainer
=> update openfiles customization in devcontainer config

src/prompts.ts
Adding some initial prompts for experimentation with Azure DevOps tools.
This pull request updates the `configurePrompts` function in `src/prompts.ts` to add new prompt configurations for Azure DevOps tools and improve existing ones. The key changes include replacing the `REPO_TOOLS` import with `CORE_TOOLS` and `WORKITEM_TOOLS`, adding new prompts for listing projects and retrieving work item details, and modifying an existing prompt to list teams instead of pull requests.
* **New Prompts Added**:
- Added a `listProjects` prompt to retrieve and display all projects in the Azure DevOps organization using the `CORE_TOOLS.list_projects` tool.
- Added a `getWorkItem` prompt to retrieve details for a specific Azure DevOps work item by ID using the `WORKITEM_TOOLS.get_work_item` tool.
* …
=> feat: add initial prompts for experimentation

.github/copilot-instructions.md
Minor change to instructions
no risk
No need for testing
=> Update pronoun for consistency in authoring instructions

.github/CODEOWNERS
Update CODEOWNERS to use maintainers tag
=> chore: update CODEOWNERS to use maintainers tag

.github/acl/access.yml
Adding members and roles
N/A
N/A
=> Adding members

src/tools/repos.ts
Previously the tool returned the error
```
status is not defined
```
Second part of #184 
/
Tested manually
=> Fixing bug with update_pull_request_status (Issue #184)

README.md
This adds typical widgets useful for adoption and contributions.
=> Add contributors and star history to readme

test/src/tools/core.test.ts
Improve Core code coverage from;
```sh
core.ts  |   89.28 |       70 |      60 |    92.3 | 17-18
```
to
```sh
File            | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s …
```
=> add core tests to improve code coverage

test/src/tools/work.test.ts
Improve Work code coverage from;
```sh
work.ts       |     100 |       75 |     100 |     100 | 39-77,97,145
```
to
```sh
File            | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s …
```
=> add work tests to improve code coverage

.github/acl/access.yml
=> Add mkonjikovac

.github/workflows/build.yml, docs/TROUBLESHOOTING.md, package-lock.json, package.json, src/index.ts
Allow explicit tenant selection for users that have accounts in multiple tenants.
Add troubleshooting guide.
Kudos to @jzworkman for submitting suggested code changes to address the issue.
https://github.com/microsoft/azure-devops-mcp/issues/148
_Replace_ by possible risks this pull request can bring you might have thought of
Tested command line options.
Tested both `mcp.json` versions with and without tenant parameter. Executed "list ADO projects" prompt for verification that REST API auth works
=> feat: support for tenant selection for auth

docs/HOWTO.md
Adding some instructions on using adding MCP Server to Claude Code
N/A
Manual review
=> docs: Update to include Claude Code instructions

package-lock.json, package.json, src/version.ts
Time to publish new version with recent changes
=> chore: publish version bump

package-lock.json, package.json, src/version.ts
=> chore: publish 1.2.1

src/tools.ts, src/tools/auth.ts, src/tools/builds.ts, src/tools/core.ts, src/tools/repos.ts, test/src/tools/builds.test.ts, test/src/tools/core.test.ts, test/src/tools/repos.test.ts
Adding UserAgent where it was missing.
None.
None.
Ran the tests. Tested some of the tools manually.
=> Adding UserAgent where it was missing

README.md, docs/EXAMPLES.md, src/prompts.ts, src/tools/wiki.ts, test/src/tools/wiki.test.ts
- Updating Readme to remove some outdated material and updated new tools
- Added new tests to get 100% coverage on wiki
- Remove Comment param from update_wiki_content as it does not appear to work at all
- Added new examples for wiki 
n/a
No risk
re-ran all automated tests and validated the changes by running locally
=> Series of misc changes

src/tools/wiki.ts, test/src/tools/wiki.test.ts
Fixes #170 
None
Run `npm run test`
=> feat: enhance wiki tool to support URL retrieval, adding tests, and improved error handling

src/tools/wiki.ts, test/src/tools/wiki.test.ts
Added new tool to fetch wiki page meta data
#537 
None
Manual testing
Added unit tests and ran
=> Added new tool to get wiki page

docs/TROUBLESHOOTING.md
Adding some content to address this common issue
None
Manual review
=> updates to troublshooting doc

src/tools/repositories.ts, test/src/tools/repositories.test.ts
Adding autocomplete options for PRs
Fixes #449 
/
Manually and added new tests.
=> Autocomplete options for PRs

docs/GETTINGSTARTED.md
Removed recommendation for Visual Studio Code in favor of Visual Studio 2022.
=> Update Visual Studio recommendation in GETTINGSTARTED.md
